"""Contratos estructurales: cada adaptador puede sustituirse sin heredar clases."""
from __future__ import annotations

from decimal import Decimal
from typing import Protocol
from uuid import UUID

from domain.orders import NewOrder


class CatalogRepository(Protocol):
    def list_active(self) -> list[dict]: ...


class SalesRepository(Protocol):
    def dashboard(self) -> dict: ...
    def record(self, product_id: int, quantity: Decimal) -> int | None: ...


class OrderRepository(Protocol):
    """Una instancia por transacción; los bloqueos duran hasta commit/rollback.

    find_request serializa reintentos del mismo propietario/clave.
    get_owned bloquea la fila y limita la lectura al propietario.
    active_products conserva los precios durante la creación.
    settle persiste el estado y las ventas históricas de forma atómica.
    """
    def find_request(self, owner: UUID, request_key: UUID) -> dict | None: ...
    def active_products(self, ids: list[int]) -> list[dict]: ...
    def create(self, owner: UUID, command: NewOrder, digest: str, mode: str,
               total: int, charge: int, currency: str, lines: list[tuple]) -> dict: ...
    def get_owned(self, order_id: UUID, owner: UUID) -> dict | None: ...
    def items(self, order_id: UUID) -> list[dict]: ...
    def save_checkout(self, order_id: UUID, reference: str, url: str) -> None: ...
    def set_status(self, order_id: UUID, status: str) -> None: ...
    def settle(self, order_id: UUID, status: str, payment_id: str) -> None: ...
    def pending(self, mode: str) -> list[dict]: ...


class PaymentProvider(Protocol):
    def start(self, order: dict) -> tuple[str, str]: ...
    def verify(self, order: dict, capture: bool = False) -> str | None: ...


class Payments(Protocol):
    def configuration(self) -> dict: ...
    def mode(self) -> str: ...
    def usd_rate(self) -> Decimal: ...
    def start(self, order: dict) -> tuple[str, str]: ...
    def verify(self, order: dict, capture: bool = False) -> str | None: ...
